### ISSUE TITLE
Few issues/suggestions

### ISSUE THREAD

**Issue by ImFascinated** [motzel/scoresaber-reloaded#18] opened 2021-10-01 12:15 UTC
Bugs:
- When linking a twitch account, after linking it the button doesn't go away.

Suggestions:
- A way to disable the score sliding in animation.
- Something to show that the twitch account was linked to a user when clicking "Link"
- Adding daily pp gain

**Comment by motzel** [comment] 2021-10-02 19:27
What do you mean by "twitch button"? The one in Settings or the one on the player avatar? As for the latter, it is left by design so that you can correct a possible wrong choice or switch to another one if a Twitch user changes it. But I might actually add a toggle in Settings so it can be hidden.

Suggestions: 

Ad 1.  What is the reason?
Ad 2. Good idea! 👍
Ad 3. Definitely on the to do list

**Comment by ImFascinated** [comment] 2021-10-03 17:27
For the animation, I really don't like it (lol) so a toggle for it could be nice.
The "twitch button" in next the the avatar, you could change it to show a "re-link" text instead of link, just a nice QOL thing.

Thanks for reading it :)

**Comment by motzel** [comment] 2021-10-04 09:33
I have added separate issues, I am closing this one.

Thanks for your suggestions!

**Closed by motzel** 2021-10-04 09:33 UTC
